<!DOCTYPE html>
<html>
    <head>
       <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>e-learner</title>
        <link rel="stylesheet" href="css/bootstrap.css" type="text/css"/>
         <link href="css/style.css" rel="stylesheet" type="text/css">
         <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
         
    </head>
    <body>
     <div class="container">
         <?php
         include 'Includes/navigation.php';
         
          if(!isset($_SESSION['user'])){
             header("location:login.php"); 
         }else{    
             if($_SESSION['role']!="RL03") {
               header("location:index.php");   
             }        
         }
         
         ?>
          <br/>
           <br/>
           <div class="container"><br/><br/>
          <table class="table table-responsive">
              <thead>
                  <tr>
                      <td class="col-sm-3">File</td>
                      <td class="col-sm-3">Download</td>
                      <td class="col-sm-4"></td>
                  </tr>
              </thead>
              <tbody>
      <?php

// Error reporting:
error_reporting(E_ALL^E_NOTICE);

// Including the DB connection file:
require 'pdo.php';

$extension='';
$files_array = array();


/* Opening the thumbnail directory and looping through all the thumbs: */

$dir_handle = @opendir($directory) or die("There is an error with your file directory!");

while ($file = readdir($dir_handle)) 
{
  /* Skipping the system files: */
  if($file{0}=='.') continue;
  
  /* end() returns the last element of the array generated by the explode() function: */
  $parts = explode('.',$file);
  $extension = strtolower(end($parts));
  
  /* Skipping the php files: */
  if($extension == 'php') continue;

  $files_array[]=$file;
}


$file_downloads=array();
$con=mysqli_connect('localhost', 'root', '', 'virtual_learner');
$cid = (isset($_GET['CourseId']) ? $_GET['CourseId'] : null);
$result = mysqli_query($con, "SELECT * FROM myfiles where CourseId='$cid'");

if(mysqli_num_rows($result))
while($row=mysqli_fetch_assoc($result))
{
  /*  The key of the $file_downloads array will be the name of the file,
    and will contain the number of downloads: */
    
  $file_downloads[$row['fichier']];
}

?>

    <?php 

        foreach($files_array as $key=>$val)
        {
          echo '<tr>';
                      echo '<td class="col-sm-3" >'.$val.'</br></td>';
                     echo '<td class="col-sm-3"><a href="download.php?fichier='.urlencode($val).'">Download</a></br></td>';
                 echo '</tr>';
        }
    
    ?>
           
              </tbody>
          </table>
           </div>
          <br/>
          <div class="container footer">
          <p>  &copy; e-learner 2015 </p>
        </div>
         </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
         <script src="js/bootstrap.js"></script>
    </body>
</html>

